[0m04:26:12.932088 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fee517e66d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fee4fcf4280>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fee4fcf4220>]}


============================== 04:26:12.938151 | d54597f5-7e6f-41ca-bf55-4b8094366859 ==============================
[0m04:26:12.938151 [info ] [MainThread]: Running with dbt=1.8.1
[0m04:26:12.939417 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/ec2-user/.dbt', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'warn_error': 'None', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'invocation_command': 'dbt init classicmodels_modeling', 'log_format': 'default', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m04:26:12.952176 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse logging event dictionary. Failed to parse dir field: expected string or bytes-like object.. Dictionary: {'dir': PosixPath('/home/ec2-user/.dbt')}
[0m04:26:12.952921 [info ] [MainThread]: Creating dbt configuration folder at 
[0m04:26:12.956383 [debug] [MainThread]: Starter project path: /home/ec2-user/environment/lab-venv/lib64/python3.9/site-packages/dbt/include/starter_project
[0m04:26:12.961897 [info ] [MainThread]: 
Your new dbt project "classicmodels_modeling" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m04:26:12.963554 [info ] [MainThread]: Setting up your profile.
[0m04:26:36.730715 [error] [MainThread]: Encountered an error:

[0m04:26:36.733738 [error] [MainThread]: Traceback (most recent call last):
  File "/home/ec2-user/environment/lab-venv/lib64/python3.9/site-packages/dbt/cli/requires.py", line 138, in wrapper
    result, success = func(*args, **kwargs)
  File "/home/ec2-user/environment/lab-venv/lib64/python3.9/site-packages/dbt/cli/requires.py", line 101, in wrapper
    return func(*args, **kwargs)
  File "/home/ec2-user/environment/lab-venv/lib64/python3.9/site-packages/dbt/cli/main.py", line 469, in init
    results = task.run()
  File "/home/ec2-user/environment/lab-venv/lib64/python3.9/site-packages/dbt/task/init.py", line 347, in run
    self.setup_profile(profile_name)
  File "/home/ec2-user/environment/lab-venv/lib64/python3.9/site-packages/dbt/task/init.py", line 263, in setup_profile
    self.create_profile_from_target(adapter, profile_name=profile_name)
  File "/home/ec2-user/environment/lab-venv/lib64/python3.9/site-packages/dbt/task/init.py", line 180, in create_profile_from_target
    self.create_profile_from_profile_template(profile_template, profile_name)
  File "/home/ec2-user/environment/lab-venv/lib64/python3.9/site-packages/dbt/task/init.py", line 164, in create_profile_from_profile_template
    target = self.generate_target_from_input(prompts, initial_target)
  File "/home/ec2-user/environment/lab-venv/lib64/python3.9/site-packages/dbt/task/init.py", line 130, in generate_target_from_input
    target[key] = click.prompt(
  File "/home/ec2-user/environment/lab-venv/lib64/python3.9/site-packages/click/termui.py", line 164, in prompt
    value = prompt_func(prompt)
  File "/home/ec2-user/environment/lab-venv/lib64/python3.9/site-packages/click/termui.py", line 147, in prompt_func
    raise Abort() from None
click.exceptions.Abort

[0m04:26:36.741583 [debug] [MainThread]: Resource report: {"command_name": "init", "command_wall_clock_time": 23.877144, "process_user_time": 1.60961, "process_kernel_time": 0.144159, "process_mem_max_rss": "87784", "process_in_blocks": "144", "process_out_blocks": "64", "command_success": false}
[0m04:26:36.744755 [debug] [MainThread]: Command `dbt init` failed at 04:26:36.744151 after 23.88 seconds
[0m04:26:36.746020 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fee517e66d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fee51aed7f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fee4f81f4c0>]}
[0m04:26:36.748398 [debug] [MainThread]: Flushing usage events
